### PR TITLE
Change Conventions to extend the cargo convention among many others.

### PR DESCRIPTION
**Pull request by jutoft**

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for providing the pull request.

Some requests from my end:

1. Can we please break up the pull request? This PR contains multiple concerns e.g. introduce `Provider` types, change to the build script etc. Let's start small by just making the changes to the build script.
2. It looks like one of the tests failing. You'll have to fix it before we can merge.
3. There are changes that will also be made by another outstanding pull request: https://github.com/bmuschko/gradle-cargo-plugin/pull/180. I'd like to get that merged first.

**Comment by bmuschko** [comment]
Hi, just checking in. Would you mind breaking up your pull request into different aspects? I merged https://github.com/bmuschko/gradle-cargo-plugin/pull/180 in the meantime.

**Comment by jutoft** [comment]
Hey.

Yes i would like to do so as soon as possible, but it will probably not be
this week.
It has been difficult to keep up with all the changes so now the pr have
become a bit broken.


tir. 29. jan. 2019 18.52 skrev Benjamin Muschko <notifications@github.com>:

**Comment by bmuschko** [comment]
I understand. I suggest you start from scratch and break out small PRs that can be merged quickly. Thanks for your work!

**Pull request closed without merging**
