### PR TITLE
cargo home directory is not an @Input, hashing can run into problems with locked files

### PR DESCRIPTION
**Pull request by samdha**
Maybe incomplete fix for #131

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Comment by samdha** [comment]
Thanks.

Do you have a date in mind for a release that includes this?

**Comment by bmuschko** [comment]
It is released.

**Comment by samdha** [comment]
Excellent. I should pay more attention. Thanks very much.

**Pull request merged**
